[package]
name = "msnchat-rs"
version = "0.2.3"
edition = "2024"

[build-dependencies]
static_vcruntime = "2.0"
windows-core = "0.61"
winres = "0.1"

[dependencies]
rand = "0.9"

[dependencies.windows]
version = "0.61"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Security",
    "Win32_UI_Shell",
    "Win32_Storage_FileSystem",
    "Win32_System",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_System_Memory",
    "Win32_System_Registry",
    "Win32_System_Ole",
    "Win32_System_Com",
    "Win32_System_Variant",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi"
]

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1