[package]
name = "mshtml"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.windows]
version = "0.61" # Use a recent stable version of the windows crate
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_System",
    "Win32_System_SystemServices",
    "Win32_System_Memory",
    "Win32_System_Registry",
    "Win32_System",
    "Win32_System_Ole",
    "Win32_System_Com",
    "Win32_UI_HiDpi",
    "Win32_UI_Controls",
    "Win32_System_Variant"
]

[dependencies.windows-core]
version = "0.61"